import { and, eq, gte, isNull } from 'drizzle-orm';
import type { Database } from '../client.js';
import {
  devicePairingTokens,
  devices,
  type Device,
  type DevicePairingToken,
  type NewDevice,
  type NewDevicePairingToken,
} from '../schema/users.js';

/**
 * Device & pairing-token queries.
 *
 * Pairing flow:
 *   1. Admin (web UI) → createPairingToken → returns a 6-char code
 *      shown as a QR + raw text. Token hash stored, plaintext shown once.
 *   2. Android app scans/types the code → consumePairingToken returns
 *      the pairing row (or null) atomically.
 *   3. Android registers itself via createDevice → returns Device row
 *      with the chosen apiKeyHash. The plaintext key is generated by
 *      the route, stored hashed.
 */

export async function createPairingToken(
  db: Database,
  args: {
    userId: string;
    codeHash: string;
    ttlMinutes?: number;
  },
): Promise<DevicePairingToken> {
  const ttl = args.ttlMinutes ?? 10;
  const expiresAt = new Date(Date.now() + ttl * 60 * 1000);
  const row: NewDevicePairingToken = {
    userId: args.userId,
    codeHash: args.codeHash,
    expiresAt,
  };
  const [inserted] = await db.insert(devicePairingTokens).values(row).returning();
  if (!inserted) throw new Error('pairing_token insert returned no rows');
  return inserted;
}

/**
 * Atomically claim a pairing token. Returns the row + ok=true on first
 * successful claim. Subsequent claims of the same token return ok=false.
 */
export async function consumePairingToken(
  db: Database,
  codeHash: string,
): Promise<{ ok: true; row: DevicePairingToken } | { ok: false }> {
  // Atomic: UPDATE ... RETURNING with the WHERE clause guarding on
  // consumed_at IS NULL ensures only one claim succeeds.
  const [row] = await db
    .update(devicePairingTokens)
    .set({ consumedAt: new Date() })
    .where(
      and(
        eq(devicePairingTokens.codeHash, codeHash),
        isNull(devicePairingTokens.consumedAt),
        gte(devicePairingTokens.expiresAt, new Date()),
      ),
    )
    .returning();
  if (!row) return { ok: false };
  return { ok: true, row };
}

export async function createDevice(
  db: Database,
  row: NewDevice,
): Promise<Device> {
  const [inserted] = await db.insert(devices).values(row).returning();
  if (!inserted) throw new Error('device insert returned no rows');
  return inserted;
}

export async function findDeviceByApiKeyHash(
  db: Database,
  apiKeyHash: string,
): Promise<Device | null> {
  const [row] = await db
    .select()
    .from(devices)
    .where(and(eq(devices.apiKeyHash, apiKeyHash), isNull(devices.revokedAt)))
    .limit(1);
  return row ?? null;
}

export async function updateDeviceFcmToken(
  db: Database,
  deviceId: string,
  fcmToken: string | null,
): Promise<void> {
  await db
    .update(devices)
    .set({ fcmToken, lastSeenAt: new Date() })
    .where(eq(devices.id, deviceId));
}

export async function touchDevice(db: Database, deviceId: string): Promise<void> {
  await db
    .update(devices)
    .set({ lastSeenAt: new Date() })
    .where(eq(devices.id, deviceId));
}

export async function revokeDevice(db: Database, deviceId: string): Promise<void> {
  await db
    .update(devices)
    .set({ revokedAt: new Date() })
    .where(eq(devices.id, deviceId));
}

export async function listDevicesForUser(
  db: Database,
  userId: string,
): Promise<Device[]> {
  return db.select().from(devices).where(eq(devices.userId, userId));
}
