import { sql } from 'drizzle-orm';
import { boolean, index, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { devicePlatformEnum, userRoleEnum } from './enums';

/**
 * Users table. v1 has exactly one row (Islam) but is future-proofed for
 * multi-user / RBAC without a schema migration — just INSERT new rows.
 */
export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  displayName: text('display_name').notNull(),
  role: userRoleEnum('role').notNull().default('super_admin'),
  telegramUserId: text('telegram_user_id').unique(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .default(sql`now()`),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

/**
 * Devices = paired clients (Android phone, web browser session, future iOS).
 * Each has its own API key (hashed) + FCM token for push.
 */
export const devices = pgTable(
  'devices',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    platform: devicePlatformEnum('platform').notNull(),
    fcmToken: text('fcm_token'),
    apiKeyHash: text('api_key_hash').notNull(),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    pushEnabled: boolean('push_enabled').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userIdx: index('devices_user_idx').on(t.userId),
  }),
);

export type Device = typeof devices.$inferSelect;
export type NewDevice = typeof devices.$inferInsert;

/**
 * Short-lived device pairing tokens. Generated by the web UI, consumed by
 * the Android app on first launch via QR code.
 */
export const devicePairingTokens = pgTable('device_pairing_tokens', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  codeHash: text('code_hash').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  consumedAt: timestamp('consumed_at', { withTimezone: true }),
  consumedByDeviceId: uuid('consumed_by_device_id').references(() => devices.id, {
    onDelete: 'set null',
  }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type DevicePairingToken = typeof devicePairingTokens.$inferSelect;
export type NewDevicePairingToken = typeof devicePairingTokens.$inferInsert;
